package com.myportfolio.mycookingrecipes.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1D6D00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF95FB71)
val md_theme_light_onPrimaryContainer = Color(0xFF042100)
val md_theme_light_secondary = Color(0xFF446900)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFADF832)
val md_theme_light_onSecondaryContainer = Color(0xFF111F00)
val md_theme_light_tertiary = Color(0xFF566500)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD8ED76)
val md_theme_light_onTertiaryContainer = Color(0xFF181E00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7FFEC)
val md_theme_light_onBackground = Color(0xFF082100)
val md_theme_light_surface = Color(0xFFF7FFEC)
val md_theme_light_onSurface = Color(0xFF082100)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFCEFFAE)
val md_theme_light_inverseSurface = Color(0xFF133800)
val md_theme_light_inversePrimary = Color(0xFF7ADD58)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1D6D00)
val md_theme_light_outlineVariant = Color(0xFFC3C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7ADD58)
val md_theme_dark_onPrimary = Color(0xFF0B3900)
val md_theme_dark_primaryContainer = Color(0xFF145200)
val md_theme_dark_onPrimaryContainer = Color(0xFF95FB71)
val md_theme_dark_secondary = Color(0xFF93DB00)
val md_theme_dark_onSecondary = Color(0xFF213600)
val md_theme_dark_secondaryContainer = Color(0xFF324F00)
val md_theme_dark_onSecondaryContainer = Color(0xFFADF832)
val md_theme_dark_tertiary = Color(0xFFBCD05D)
val md_theme_dark_onTertiary = Color(0xFF2C3400)
val md_theme_dark_tertiaryContainer = Color(0xFF404C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFD8ED76)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF082100)
val md_theme_dark_onBackground = Color(0xFFB9F396)
val md_theme_dark_surface = Color(0xFF082100)
val md_theme_dark_onSurface = Color(0xFFB9F396)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)
val md_theme_dark_outline = Color(0xFF8D9387)
val md_theme_dark_inverseOnSurface = Color(0xFF082100)
val md_theme_dark_inverseSurface = Color(0xFFB9F396)
val md_theme_dark_inversePrimary = Color(0xFF1D6D00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7ADD58)
val md_theme_dark_outlineVariant = Color(0xFF43483F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF278900)
